# Generated by Django 3.2.6 on 2021-08-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavesdata',
            old_name='remaing_leave_monthly',
            new_name='remaining_leave_monthly',
        ),
        migrations.RenameField(
            model_name='leavesdata',
            old_name='remaing_leave_yearly',
            new_name='remaining_leave_yearly',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leave_remaining',
        ),
        migrations.AddField(
            model_name='leavesdata',
            name='paid_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavesdata',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Login.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='leavesdata',
            unique_together={('leave_type', 'user_name')},
        ),
    ]
