# Generated by Django 3.2.6 on 2021-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20210825_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='rejected_reason',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
