# Generated by Django 3.2.6 on 2021-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_leaverequests_rejected_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequests',
            name='rejected_reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
